name: choco
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ðŸ“¦ ÐŸÐ°ÐºÐµÑ‚Ñ‚ÐµÑ€
  url_launcher: ^6.1.7
  http: ^1.2.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/cake1.png
    - assets/cake_bg.jpg
    - assets/donut_bottom_right.png
    - assets/donut_top_left.png
    - assets/special_offer_image_1.png
    - assets/special_offer_image_2.png
    - assets/product_1.png
    - assets/product_2.png
    - assets/product_3.png
    - assets/product_4.png
    - assets/advertisement_banner.png
    - assets/tort_snikers.png
    - assets/tort_napoleon.png
    - assets/bento_dr.png
    - assets/bento_friend.png
    - assets/bento_love.png
    - assets/bento_minimalizm.png
    - assets/bento_morkovnyy.png
    - assets/bento_redvelvet.png
    - assets/bento_shokolad.png
    - assets/bento_surprise.png
    - assets/bento_tropiki.png
    - assets/macarons_fistashka.png
    - assets/macarons_lavanda.png
    - assets/macarons_limon.png
    - assets/macarons_malina.png
    - assets/macarons_mango.png
    - assets/macarons_premium.png
    - assets/macarons_shokolad.png
    - assets/macarons_karamel.png
    - assets/macarons_kofe.png
    - assets/napitki_amerikano.png
    - assets/napitki_ayslatte.png
    - assets/napitki_goryachiy_shokolad.png
    - assets/napitki_kapuchino.png
    - assets/napitki_milksheyik.png
    - assets/napitki_mohito.png
    - assets/napitki_sok_apelsin.png
    - assets/napitki_sok_vishnya.png
    - assets/pirojnoe_banan.png
    - assets/pirojnoe_kartoshka.png
    - assets/pirojnoe_maffin_chernika.png
    - assets/pirojnoe_muraveynik.png
    - assets/pirojnoe_pavlova.png
    - assets/pirojnoe_redvelvet.png
    - assets/pirojnoe_trishokolada.png
    - assets/pirojnoe_trubochka.png
    - assets/tort_morkovnyy.png
    - assets/tort_praga.png
    - assets/tort_ptichyemoloko.png
    - assets/tort_tiramisu.png
    - assets/vypechka_kish.png
    - assets/vypechka_kruassan.png
    - assets/vypechka_mak.png
    - assets/vypechka_pirog_vishnya.png
    - assets/vypechka_ponchik.png
    - assets/vypechka_sinnabon.png
    - assets/vypechka_sochnik.png
    - assets/vypechka_sosiska.png
